#include "esp_log.h"
#include "esp_wifi.h"
#include "nvs_flash.h"

#include "iot_utils.h"


void initialize_device(void)
{
    // Initialize the flash memory, erasing the entirety of its contents if
    // there are no free pages.
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES)
    {
        ESP_ERROR_CHECK( nvs_flash_erase() );
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK( ret );

    // Disable logging originating from within the wifi driver and initialize
    // the TCP/IP adapter.
    esp_log_level_set("wifi", ESP_LOG_NONE);
    tcpip_adapter_init();

    // Configure the wifi peripheral, setting the default configuration
    // generated by the ESP-IDF SDK as well as its default storage and
    // operating mode.
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK( esp_wifi_init(&cfg) );
    ESP_ERROR_CHECK( esp_wifi_set_storage(WIFI_STORAGE_RAM) );
    ESP_ERROR_CHECK( esp_wifi_set_mode(WIFI_MODE_STA) );
}

void connect_to_wifi_network(const char *ssid, const char *pass)
{
    // Populate the configuration struct with the provided SSID and password.
    wifi_config_t sta_config = {
        .sta = {}
    };
    memcpy(sta_config.sta.ssid,     ssid, strlen(ssid));
    memcpy(sta_config.sta.password, pass, strlen(pass));

    // Attempt to connect to the network using the above configuration struct.
    ESP_ERROR_CHECK( esp_wifi_set_config(WIFI_IF_STA, &sta_config) );
    ESP_ERROR_CHECK( esp_wifi_start() );
    ESP_ERROR_CHECK( esp_wifi_connect() );
}

void connect_to_mqtt_broker(
    const char *uri, esp_err_t (* fn)(esp_mqtt_event_handle_t)
)
{
    // Populate the configuration struct with the provided URI and a pointer
    // to the event handler function before initializing and starting the
    // MQTT client.
    const esp_mqtt_client_config_t mqtt_cfg = {
        .uri          = uri,
        .event_handle = fn,
    };
    esp_mqtt_client_handle_t client = esp_mqtt_client_init(&mqtt_cfg);
    esp_mqtt_client_start(client);
}
