/*****************************************************************************
 * TODO: document me
 *****************************************************************************/

#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"

#include "nvs_flash.h"

#include "esp_event.h"
#include "esp_event_loop.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_wifi.h"

#include "sdkconfig.h"


///////////////////////////////////////////////////////////////////////////////
// CONSTANTS & GLOBALS

static const char *TAG          = "ESP-IOT-QUICKSTART";
const int         CONNECTED_BIT = BIT0;

static EventGroupHandle_t wifi_event_group = NULL;


///////////////////////////////////////////////////////////////////////////////
// INITIALIZATION & CONFIGURATION

void initialize_device(void)
{
    // Initialize the flash memory, erasing the entirety of its contents if
    // there are no free pages.
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES)
    {
        ESP_ERROR_CHECK( nvs_flash_erase() );
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK( ret );

    // Disable logging originating from within the wifi driver, initialize the
    // TCP/IP adapter, and create the wifi event group.
    esp_log_level_set("wifi", ESP_LOG_NONE);
    tcpip_adapter_init();
    wifi_event_group = xEventGroupCreate();

    // Configure the wifi peripheral, setting the default configuration
    // generated by the ESP-IDF SDK as well as its default storage and
    // operating mode.
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK( esp_wifi_init(&cfg) );
    ESP_ERROR_CHECK( esp_wifi_set_storage(WIFI_STORAGE_RAM) );
    ESP_ERROR_CHECK( esp_wifi_set_mode(WIFI_MODE_STA) );
}


///////////////////////////////////////////////////////////////////////////////
// EVENT HANDLERS

void wifi_connect(void)
{
    wifi_config_t sta_config = {
        .sta = {
            .ssid      = CONFIG_ESP_WIFI_SSID,
            .password  = CONFIG_ESP_WIFI_PASSWORD,
            .bssid_set = false
        }
    };
    ESP_ERROR_CHECK( esp_wifi_set_config(WIFI_IF_STA, &sta_config) );
    ESP_ERROR_CHECK( esp_wifi_start() );
    ESP_ERROR_CHECK( esp_wifi_connect() );
}

esp_err_t wifi_event_handler(void *ctx, system_event_t *event)
{
    switch (event->event_id)
    {
    case SYSTEM_EVENT_STA_START:
        wifi_connect();
        break;
    case SYSTEM_EVENT_STA_GOT_IP:
        xEventGroupSetBits(wifi_event_group, CONNECTED_BIT);
        break;
    case SYSTEM_EVENT_STA_DISCONNECTED:
        esp_wifi_connect();
        xEventGroupClearBits(wifi_event_group, CONNECTED_BIT);
        break;
    default:
        break;
    }

    return ESP_OK;
}


///////////////////////////////////////////////////////////////////////////////
// MAIN

void app_main(void)
{
    ESP_LOGI(TAG, "Application starting...");
    ESP_LOGI(TAG, "IDF version: %s", esp_get_idf_version());

    // perform any necessary initialization/configuration of the device and its
    // peripherals
    initialize_device();
    ESP_LOGI(TAG, "Non-volatile storage initialized");

    // set the event loop handler for wifi and start the wifi peripheral
    ESP_ERROR_CHECK( esp_event_loop_init(wifi_event_handler, NULL) );
    ESP_LOGI(TAG, "Starting wifi...");
    ESP_ERROR_CHECK( esp_wifi_start() );
}
